### ISSUE TITLE
Exometer creates extra directories

### ISSUE THREAD

**Issue by eproxus** [Feuerlabs/exometer_core#58]
When running Exometer, two extra directories are created:

```
data.nonode@nohost log.nonode@nohost
```

**Comment by uwiger** [comment]
This would be easiest to avoid by instructing `setup` via the environment variable `{verify_directories, false}`.

https://github.com/uwiger/setup/blob/1.6/doc/setup.md#customizing-setup

For this to work, `exometer_core` would need to be updated to depend on `setup` 1.6 instead of 1.5, which should be done anyway, since 1.6 removes `io:fwrite` calls and fixes some env var expansion bugs too.

**Comment by tolbrino** [comment]
@uwiger I was about to say, that we should create a new release for setup :+1:

**Comment by eproxus** [comment]
Why does Exometer depend on `setup`?

**Comment by uwiger** [comment]
@eproxus Exometer uses `setup` for environment variable expansion and for finding exometer configs specified in other application environments (the variables `exometer_defaults`, `exometer_predefined`, `exometer_folsom_monitor`, `exometer_reporters`, and `exometer_subscribers`.)

The variable expansion support in setup is documented here: https://github.com/uwiger/setup/blob/master/doc/setup.md#variable-expansion
The most likely feature used in exometer_core configs would probably be the `$PRIV_DIR` variable.

**Comment by eproxus** [comment]
Ok, sounds reasonable. I'll verify once `setup` is updated to 1.6 and then close this issue.

**Comment by eproxus** [comment]
Ok, verified working on latest master. Thanks!
